/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PIDI1.c
**     Project     : Encoder
**     Processor   : MK64FN1M0VLL12
**     Component   : PID_Int
**     Version     : Component 01.001, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-05-04, 18:07, # CodeGen: 28
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Control  - void PIDI1_Control(void);
**         SetPoint - void PIDI1_SetPoint(int16_t value);
**         GetPoint - int16_t PIDI1_GetPoint(void);
**         Enable   - void PIDI1_Enable(void);
**         Disable  - void PIDI1_Disable(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file PIDI1.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup PIDI1_module PIDI1 module documentation
**  @{
*/         

/* MODULE PIDI1. */

#include "PIDI1.h"

static int PIDI1_setPoint; /* the value to be reached by the PID algorithm */
static bool PIDI1_disabled;  /* if the PID controller is enabled or not */

/*
** ===================================================================
**     Method      :  PIDI1_Control (component PID_Int)
**     Description :
**         Performs the PID control calculation.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#ifdef __HIWARE__
#pragma MESSAGE DISABLE C5904 /* Division by one */
#pragma MESSAGE DISABLE C5905 /* Multiplication with one */
#endif
static const int PIDI1_KpMul = 1, PIDI1_KpDiv = 8; /* the Kp adjustment values */
static const int PIDI1_KiMul = 1, PIDI1_KiDiv = 512; /* the Ki adjustment values */
static const int PIDI1_KdMul = 4, PIDI1_KdDiv = 1; /* the Kd adjustment values */

void PIDI1_Control(void)
{
  /* Performs a PID calculation. The set point is specified by 'PIDI1_SetPoint()' */
  static int oldRegelDiff = 0; /*!< Remember error for next round (for D part) */
  static int regIntegral = 0;  /*!< Remember integral part for next iteration */
  int regelDiff; /* actual error */
  int setPoint;  /* new set point */
  int regDifferential; /* temporary variable for the D part */
  word currActorValue; /* current values from actuator */

  if (PIDI1_disabled) { /* PID disabled? */
    return; /* do nothing */
  }
  regelDiff = PIDI1_setPoint-Tacho1_GetVal();
  if (PIDI1_setPoint == 0) {
    MAX1_SetVal(0);
    return; /* all done, this was easy :-) */
  }
  setPoint = 0;

  /* P-Part */
  setPoint += (PIDI1_KpMul*regelDiff)/PIDI1_KpDiv;

  /* I-Part */
  regIntegral += regelDiff;
  if (regIntegral > 1024) { /* anti wind-up */
    regIntegral = 1024;
  } else if (regIntegral < -1024) {
    regIntegral = -1024;
  }
  setPoint += (PIDI1_KiMul*regIntegral)/PIDI1_KiDiv;

  /* D-Part */
  regDifferential = regelDiff-oldRegelDiff;
  oldRegelDiff = regelDiff; /* remember for next iteration */
  setPoint += (PIDI1_KdMul*regDifferential)/PIDI1_KdDiv; /* scaled down by a factor to avoid overreaction */

  if (setPoint == 0) {
    return; /* nothing to do */
  }

  currActorValue = MAX1_GetVal();
  if (setPoint > 0) { /* increase actuator value */
    if (currActorValue >= (0xFFFF-setPoint)) { /* check for overflow */
      MAX1_SetVal(0xFFFF);
    } else {
      MAX1_SetVal((word)(currActorValue+setPoint));
    }
  } else { /* setPoint < 0, decrease actuator value */
    setPoint = -setPoint;
    if (setPoint >= currActorValue) { /* check for underflow */
      MAX1_SetVal(0);
    } else {
      MAX1_SetVal((word)(currActorValue-setPoint));
    }
  }
}

/*
** ===================================================================
**     Method      :  PIDI1_SetPoint (component PID_Int)
**     Description :
**         Specifies the value to be reached by the PID controller.
**     Parameters  :
**         NAME            - DESCRIPTION
**         value           - The setpoint value.
**     Returns     : Nothing
** ===================================================================
*/
void PIDI1_SetPoint(int value)
{
  PIDI1_setPoint = value;
}

/*
** ===================================================================
**     Method      :  PIDI1_Enable (component PID_Int)
**     Description :
**         Enables the PID controller.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PIDI1_Enable(void)
{
  PIDI1_disabled = 0;
}

/*
** ===================================================================
**     Method      :  PIDI1_Disable (component PID_Int)
**     Description :
**         Disables the PID controller.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PIDI1_Disable(void)
{
  PIDI1_disabled = 1;
}

/*
** ===================================================================
**     Method      :  PIDI1_GetPoint (component PID_Int)
**     Description :
**         Returns the current set point value
**     Parameters  : None
**     Returns     :
**         ---             - The current set point
** ===================================================================
*/
int PIDI1_GetPoint(void)
{
  return PIDI1_setPoint;
}

/* END PIDI1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
