/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PIDI1.h
**     Project     : Encoder
**     Processor   : MK64FN1M0VLL12
**     Component   : PID_Int
**     Version     : Component 01.001, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-05-03, 16:23, # CodeGen: 25
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Control  - void PIDI1_Control(void);
**         SetPoint - void PIDI1_SetPoint(int16_t value);
**         GetPoint - int16_t PIDI1_GetPoint(void);
**         Enable   - void PIDI1_Enable(void);
**         Disable  - void PIDI1_Disable(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file PIDI1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup PIDI1_module PIDI1 module documentation
**  @{
*/         

#ifndef __PIDI1_H
#define __PIDI1_H

/* MODULE PIDI1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "Tacho1.h"
#include "MAX1.h"

#include "Cpu.h"




void PIDI1_Control(void);
/*
** ===================================================================
**     Method      :  PIDI1_Control (component PID_Int)
**     Description :
**         Performs the PID control calculation.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void PIDI1_SetPoint(int value);
/*
** ===================================================================
**     Method      :  PIDI1_SetPoint (component PID_Int)
**     Description :
**         Specifies the value to be reached by the PID controller.
**     Parameters  :
**         NAME            - DESCRIPTION
**         value           - The setpoint value.
**     Returns     : Nothing
** ===================================================================
*/

void PIDI1_Enable(void);
/*
** ===================================================================
**     Method      :  PIDI1_Enable (component PID_Int)
**     Description :
**         Enables the PID controller.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void PIDI1_Disable(void);
/*
** ===================================================================
**     Method      :  PIDI1_Disable (component PID_Int)
**     Description :
**         Disables the PID controller.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

int PIDI1_GetPoint(void);
/*
** ===================================================================
**     Method      :  PIDI1_GetPoint (component PID_Int)
**     Description :
**         Returns the current set point value
**     Parameters  : None
**     Returns     :
**         ---             - The current set point
** ===================================================================
*/

/* END PIDI1. */

#endif
/* ifndef __PIDI1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
