/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Tacho1.c
**     Project     : Encoder
**     Processor   : MK64FN1M0VLL12
**     Component   : Tacho
**     Version     : Component 01.002, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-05-02, 13:50, # CodeGen: 18
**     Abstract    :
**
This component implements a tacho to measure the speed, for example the speed of a DC motor.
**     Settings    :
**
**     Contents    :
**         Sample   - void Tacho1_Sample(void);
**         GetVal   - word Tacho1_GetVal(void);
**         GetSpeed - int16_t Tacho1_GetSpeed(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2014, all rights reserved.
**     This an open source software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Tacho1.c
** @version 01.00
** @brief
**
This component implements a tacho to measure the speed, for example the speed of a DC motor.
*/         
/*!
**  @addtogroup Tacho1_module Tacho1 module documentation
**  @{
*/         

/* MODULE Tacho1. */

#include "Tacho1.h"


#define SPEED_CALC_PERIOD ((word)2)     /* speed sample period in ms. Make sure that speed is sampled at the given rate. */
#define NOF_HISTORY (32+1U) /* number of samples for speed calculation (>0):the more, the better, but the slower. For efficient code, make it a (power of 2)+1 */
static volatile uint16_t Tacho1_PosHistory[NOF_HISTORY]; /* for better accuracy, we calculate the speed over some samples */
static volatile byte Tacho1_PosHistory_Index = 0;

/*
** ===================================================================
**     Method      :  Tacho1_GetSpeed (component Tacho)
**     Description :
**         Returns the speed (RPM) based on the position information
**         from the encoder.
**     Parameters  : None
**     Returns     :
**         ---             - Speed in RPM.
** ===================================================================
*/
int16_t Tacho1_GetSpeed(void)
{
  CS1_CriticalVariable();
  int16_t delta, pos, curr, speed;

  CS1_EnterCritical();
  curr = (int16_t)Tacho1_PosHistory[Tacho1_PosHistory_Index];
  if (Tacho1_PosHistory_Index == 0) {
    pos = (int16_t)Tacho1_PosHistory[NOF_HISTORY-1];
  } else {
    pos = (int16_t)Tacho1_PosHistory[Tacho1_PosHistory_Index-1];
  }
  CS1_ExitCritical();
  delta = curr-pos;
  if (delta < 0) {
    delta = -delta;
  }
  /* calculate speed in ticks */
  speed = ((word)delta)*16;
  return speed;
}

/*
** ===================================================================
**     Method      :  Tacho1_GetVal (component Tacho)
**     Description :
**         Returns the sensor value (RPM)
**     Parameters  : None
**     Returns     :
**         ---             - Sensor value
** ===================================================================
*/
/* this function is implemented as macro in the header file
word Tacho1_GetVal(void)
{
  return Tacho1_GetSpeed();
}
*/

/*
** ===================================================================
**     Method      :  Tacho1_Sample (component Tacho)
**     Description :
**         This method samples counter values in order to calculate the
**         speed.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Tacho1_Sample(void)
{
  Tacho1_PosHistory[Tacho1_PosHistory_Index] = Q4C1_GetPos();
  Tacho1_PosHistory_Index++;
  if (Tacho1_PosHistory_Index >= NOF_HISTORY) {
    Tacho1_PosHistory_Index = 0;
  }
}

/* END Tacho1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
